Import('*')
env = env.Clone()

# -- internal access of the OTest2 headers
env.Append(CPPPATH = ['../include/otest2'])

# -- compilation and linking flags of the libclang and LLVM
env.Append(LIBS = [
    'clangTooling',
    'clangFrontend',
    'clangFrontendTool',
    'clangSerialization',
    'clangDriver',
    'clangRewriteFrontend',
    'clangRewrite',
    'clangParse',
    'clangSema',
    'clangAnalysis',
    'clangAST',
    'clangASTMatchers',
    'clangEdit',
    'clangLex',
    'clangBasic',
])
env.ParseConfig("{0} --ldflags --libs --system-libs --cxxflags".format(llvmcfg))
env.MergeFlags('-fexceptions -std=c++14')

env.Program('otest2', [
    'error.cpp',
    'exc.cpp',
    'excparser.cpp',
    'excreader.cpp',
    'filereader.cpp',
    'formatting.cpp',
    'generator.cpp',
    'generatorprinter.cpp',
    'generatorstd.cpp',
    'generfmt.cpp',
    'lcstream.cpp',
    'location.cpp',
    'main.cpp',
    'options.cpp',
    'parser.cpp',
    'typetemplate.cpp',
    'vartable.cpp',
])