Import('*')
env = env.Clone()

env.Append(LIBPATH = ['../lib'])
env.Append(LIBS = [
    "otest2",
    'tinfo',
    'bz2',
])

# -- tested test suites
envST = env.Clone()
envST.Append(OTEST2DOMAIN = 'selftest')
envST.OTest2(env.Glob('selftests/*.ot2'))

# -- testing test suites
env.OTest2Suite('Program', 'selftest', [
    env.Glob('selftests/*.ot2.cpp'),
    'assertions.ot2',
    'base64.ot2',
    'bzip2.ot2',
    'exceptions.ot2',
    'fixtures.ot2',
    'hirschberg.ot2',
    'main.cpp',
    'mainloop.ot2',
    'regressions.ot2',
    'reportermock.cpp',
    'runtime.cpp',
    'tee.ot2',
    'testmarks.ot2',
])

# -- scons check
test_run = env.Alias('check', ['selftest'], 'test/selftest')
env.AlwaysBuild(test_run)
