version: '3.5'

services:
  jekyll:
    # -- jekyll service deamon. Run the compose from a directory
    #    where your document root is placed
    image: "jekyll/jekyll"
    hostname: "jekyll"
    volumes:
      - "jekyll-cache:/usr/gem"
      - "${PWD}:/srv/jekyll"
    command: jekyll serve
    ports:
      - "4000:4000"

volumes:
  jekyll-cache:
