version: 2.1

jobs:
  build:
    parameters:
      build-artifacts:
        type: boolean
        default: false
    docker:
      - image: staon/otest2-ci:latest
    steps:
      - checkout
      - run:
          name: Preparing Building Environment...
          command: |
            mkdir -p test-results/selftest
            mkdir -p artifacts
            mkdir -p build
            cd build
            cmake ..
      - when:
          condition: << parameters.build-artifacts >>
          steps:
            - run:
                name: Making the Source Package...
                command: |
                  cd build
                  make package_source
                  mv *.tar.gz ../artifacts
      - run:
          name: Building the Framework...
          command: |
            cd build
            make -j4
      - run:
          name: Running Selftests...
          environment:
            TERM: ansi
          command: |
            cd build
            make -j4 check-circleci
      - store_test_results:
          path: test-results
      - when:
          condition: << parameters.build-artifacts >>
          steps:
            - run:
                name: Making Binary Packages...
                command: |
                  cd build
                  make package
                  mv *.tar.gz *.deb ../artifacts
            - store_artifacts:
                path: artifacts

  doxygen:
    docker:
      - image: staon/doxygen:latest
    steps:
      - checkout
      - run:
          name: Generating API documentation...
          command: |
            doxygen
      - add_ssh_keys:
          fingerprints:
            - "95:6b:1d:ab:a7:54:44:d1:3d:b6:44:11:a4:ed:f0:c2"
      - run:
          name: Pushing generated documentation up...
          command: |
            git config user.email "stareko@email.cz"
            git config user.name "Staon"
            git add -f --all docs/api
            git diff-index --quiet HEAD || ( git commit -m "[skip ci] Generated Doxygen Documentation" && git push )

workflows:
  version: 2
  build:
    jobs:
      - build:
          build-artifacts: false
          name: "build-branch"
      - build:
          build-artifacts: true
          name: "build-release"
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v\d+[.]\d+[.]\d+.*$/
      - doxygen:
          requires: 
            - build-branch
            - build-release
          filters:
            branches:
              only: master
