version: 2
jobs:
  build:
    docker:
      - image: staon/otest2-ci:latest
    steps:
      - checkout
      - run:
          name: Build
          command: |
            mkdir -p build
            cd build
            cmake ..
            make
      - run:
          name: Run Tests
          command: |
            mkdir -p test-results/selftest
            cd build
            make check-circleci
      - store_test_results:
          path: test-results
