version: 2
jobs:
  build:
    docker:
      - image: staon/otest2-ci:latest
    steps:
      - checkout
      - run:
          name: Build
          command: scons
      - run:
          name: Run Tests
          command: |
            mkdir -p test-results/selftest
            cd test
            ./selftest --junit=../test-results/selftest/result.xml
      - store_test_results:
          path: test-results
