/*
  This file is generated by the otest2 preprocessor. Don't modify it!
*/

#include <otest2/suitegenerated.h>
#include <otest2/casegenerated.h>
#include <otest2/stategenerated.h>

#include <otest2/otest2.h>

#include <datstr/dstring.h>
#include <datstr/iptr.h>
#include <iostream>

/**
 * @brief Example test suite
 */
class ExampleSuite : public ::OTest2::SuiteGenerated {
  private:
    /* -- avoid copying */
    ExampleSuite(
        const ExampleSuite&);
    ExampleSuite& operator =(
        const ExampleSuite&);

  private:
    dstring suite_text ;

    class FirstCase : public ::OTest2::CaseGenerated {
      private:
        /* -- avoid copying */
        FirstCase(
            const FirstCase&);
        FirstCase& operator =(
            const FirstCase&);

      private:
        dstring & suite_text ;
        dstring (* (* case_var [10][20])())(dstring const * const );
        void (* case_fce )(int , char const * foo_ );
        char (* (* fce2 )())[10];
        char const * (* const (* fce3 )())[10];
        int dstring::* mptr ;
        int (dstring::* mfce )(int );
        cIPtr< dstring > temp1 ;

        class Init : public ::OTest2::StateGenerated {
          private:
            /* -- avoid copying */
            Init(
              const Init&);
            Init& operator =(
                const Init&);

          private:
            dstring & suite_text ;
            dstring (* (* (& case_var )[10][20])())(dstring const * const );
            void (* & case_fce )(int , char const * foo_ );
            char (* (* & fce2 )())[10];
            char const * (* const (* & fce3 )())[10];
            int dstring::* & mptr ;
            int (dstring::* & mfce )(int );
            cIPtr< dstring > & temp1 ;

            virtual void runState(
                const ::OTest2::Context& context_) {
      std::cout
          << suite_text << std::endl
          << case_var << std::endl
          << case_fce << std::endl
          << fce2 << std::endl
          << fce3 << std::endl;
                }

          public:
            explicit Init(
                const ::OTest2::Context& context_,
                ExampleSuite* suite_,
                FirstCase* case_) :
              ::OTest2::StateGenerated(context_),
              suite_text(case_ -> suite_text),
              case_var(case_ -> case_var),
              case_fce(case_ -> case_fce),
              fce2(case_ -> fce2),
              fce3(case_ -> fce3),
              mptr(case_ -> mptr),
              mfce(case_ -> mfce),
              temp1(case_ -> temp1) {

            }

            virtual ~Init() {

            }
        };

      public:
        explicit FirstCase(
            const ::OTest2::Context& context_,
            ExampleSuite* suite_) :
          ::OTest2::CaseGenerated(context_),
          suite_text(suite_ -> suite_text),
          case_fce(0),
          fce2(0),
          fce3(0),
          mptr(0),
          mfce(0) {

            }

        virtual ~FirstCase() {

            }
    };

  public:
    explicit ExampleSuite(
        const ::OTest2::Context& context_) :
      ::OTest2::SuiteGenerated(context_),
      suite_text("Ahoj") {
    /* -- make the string upper */
    suite_text.Toupper();
      }

    virtual ~ExampleSuite() {

    }
};

