/*
 * Copyright (C) 2018 Ondrej Starek
 *
 * This file is part of OTest2.
 *
 * OTest2 is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License,
 * or (at your option) any later version.
 *
 * OTest2 is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with OTest2.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef OTest2INCLUDE_SUITEGENERATED_H_
#define OTest2INCLUDE_SUITEGENERATED_H_

#include <string>

#include <otest2/casefactoryptr.h>
#include <otest2/contextobject.h>
#include <otest2/suiteordinary.h>

namespace OTest2 {

class Context;

/**
 * @brief Helper class for suites generated by the otest2 preprocessor
 */
class SuiteGenerated : public SuiteOrdinary, public ContextObject {
  private:
    struct Impl;
    Impl* pimpl;

  public:
    /* -- avoid copying */
    SuiteGenerated(
        const SuiteGenerated&) = delete;
    SuiteGenerated& operator =(
        const SuiteGenerated&) = delete;

    /**
     * @brief Ctor
     *
     * @param context_ OTest2 context
     * @param name_ Name of the suite
     */
    explicit SuiteGenerated(
        const Context& context_,
        const std::string& name_);

    /**
     * @brief Dtor
     */
    virtual ~SuiteGenerated();

    /* -- object */
    virtual std::string getName() const;

    /* -- context object */
    virtual const Context& otest2Context() const;

    /* -- suite ordinary */
    virtual CaseFactoryPtr getCase(
        const Context& context_,
        int index_,
        std::string* name_) const;
    virtual bool startUpSuite(
        const Context& context_,
        int index_);
    virtual void tearDownSuite(
        const Context& context_,
        int index_);

  protected:
    /**
     * @brief Register new test case
     *
     * @param name_ Name of the test case
     * @param case_factory_ A factory of the test case
     */
    void registerCase(
        const std::string& name_,
        CaseFactoryPtr case_factory_);

  private:
    /**
     * @brief User start-up code
     */
    virtual void startUp() = 0;

    /**
     * @brief User clean-up code
     */
    virtual void tearDown() = 0;
};

} /* -- namespace OTest2 */

#endif /* -- OTest2INCLUDE_SUITEGENERATED_H_ */
