#include "generatorstd.h"

#include <datstr/dstring.h>
#include <iostream>
#include <ondrart/oassert.h>
#include <ondrart/odelete.h>

#include "vartable.h"

namespace OTest2 {

namespace {

char const* const EMPTY_BODY("\n\n");

} /* -- namespace */

struct GeneratorStd::Impl {
  public:
    GeneratorStd* owner;
    std::ostream* output;

    /* -- current state */
    dstring suite;
    dstring testcase;
    dstring state;

    /* -- table of variables */
    VarTablePtr variables;
    int indent;

    /* -- bodies of the constructors and destructors */
    dstring suite_ctor;
    dstring suite_dtor;
    dstring case_ctor;
    dstring case_dtor;
    dstring state_ctor;
    dstring state_dtor;

  private:
    /* -- avoid copying */
    Impl(
        const Impl&);
    Impl& operator =(
        const Impl&);

  public:
    explicit Impl(
        GeneratorStd* owner_,
        std::ostream* output_);
    ~Impl();
};

GeneratorStd::Impl::Impl(
    GeneratorStd* owner_,
    std::ostream* output_) :
  owner(owner_),
  output(output_),
  suite(),
  testcase(),
  state(),
  variables(),
  indent(0) {

}

GeneratorStd::Impl::~Impl() {

}

GeneratorStd::GeneratorStd(
    std::ostream* output_) :
  pimpl(new Impl(this, output_)) {

}

GeneratorStd::~GeneratorStd() {

}

void GeneratorStd::beginFile() {
  *pimpl -> output
      << "/*\n"
      << "  This file is generated by the otest2 preprocessor. Don't modify it!\n"
      << "*/\n"
      << '\n'
      << "#include <otest2/suitegenerated.h>\n"
      << "#include <otest2/casegenerated.h>\n"
      << "#include <otest2/stategenerated.h>\n"
      << '\n';
}

void GeneratorStd::dumpString(
    const dstring& string_) {
//  *pimpl -> output << "dump: \"" << string_ << '"' << std::endl;
  *pimpl -> output << string_;
}

void GeneratorStd::enterSuite(
    const dstring& suite_) {
  OASSERT_1(pimpl -> suite.IsNull() && pimpl -> testcase.IsNull() && pimpl -> state.IsNull());
  OASSERT_1(!suite_.IsNullEmpty());

  pimpl -> suite = suite_;
  pimpl -> variables = new VarTable("suite_", 0);
  pimpl -> indent += 2;
  pimpl -> suite_ctor = EMPTY_BODY;
  pimpl -> suite_dtor = EMPTY_BODY;

  *pimpl -> output
      << "class " << suite_ << " : public ::OTest2::SuiteGenerated {\n"
      << "  private:\n"
      << "    /* -- avoid copying */\n"
      << "    " << suite_ << "(\n"
      << "        const " << suite_ << "&);\n"
      << "    " << suite_ << "& operator =(\n"
      << "        const " << suite_ << "&);\n"
      << '\n'
      << "  private:\n";
}

void GeneratorStd::enterCase(
    const dstring& case_) {
  OASSERT_1(!pimpl -> suite.IsNull() && pimpl -> testcase.IsNull() && pimpl -> state.IsNull());
  OASSERT_1(!case_.IsNullEmpty());

  pimpl -> testcase = case_;
  pimpl -> variables = new VarTable("case_", pimpl -> variables.ObjectAddr());
  pimpl -> indent += 2;
  pimpl -> case_ctor = EMPTY_BODY;
  pimpl -> case_dtor = EMPTY_BODY;

  *pimpl -> output
      << "    class " << case_ << " : public ::OTest2::CaseGenerated {\n"
      << "      private:\n"
      << "        /* -- avoid copying */\n"
      << "        " << case_ << "(\n"
      << "            const " << case_ << "&);\n"
      << "        " << case_ << "& operator =(\n"
      << "            const " << case_ << "&);\n"
      << '\n'
      << "      private:\n";
}

void GeneratorStd::enterState(
    const dstring& state_) {
  OASSERT_1(!pimpl -> suite.IsNull() && !pimpl -> testcase.IsNull() && pimpl -> state.IsNull());
  OASSERT_1(!state_.IsNullEmpty());

  pimpl -> state = state_;
  pimpl -> variables = new VarTable("state_", pimpl -> variables.ObjectAddr());
  pimpl -> indent += 2;
  pimpl -> state_ctor = EMPTY_BODY;
  pimpl -> state_dtor = EMPTY_BODY;

  *pimpl -> output
      << "        class " << state_ << " : public ::OTest2::StateGenerated {\n"
      << "          private:\n"
      << "            /* -- avoid copying */\n"
      << "            " << state_ << "(\n"
      << "              const " << state_ << "&);\n"
      << "            " << state_ << "& operator =(\n"
      << "                const " << state_ << "&);\n"
      << "\n"
      << "          private:\n";
  pimpl -> variables -> printDeclarations(*pimpl -> output, pimpl -> indent);
  *pimpl -> output
      << '\n'
      << "            virtual void runState(\n"
      << "                const ::OTest2::Context& context_) {";
}

void GeneratorStd::leaveState() {
  OASSERT_1(!pimpl -> suite.IsNull() && !pimpl -> testcase.IsNull() && !pimpl -> state.IsNull());

  *pimpl -> output
      << "            }\n"
      << "\n"
      << "          public:\n"
      << "            explicit " << pimpl -> state << "(\n"
      << "                const ::OTest2::Context& context_,\n"
      << "                " << pimpl -> suite << "* suite_,\n"
      << "                " << pimpl -> testcase << "* case_) :\n"
      << "              ::OTest2::StateGenerated(context_)";
  pimpl -> variables -> printInitializers(*pimpl -> output, pimpl -> indent + 1);
  *pimpl -> output
      << " {"
      << pimpl -> state_ctor
      << "            }\n"
      << "\n"
      << "            virtual ~" << pimpl -> state << "() {"
      << pimpl -> state_dtor
      << "            }\n"
      << "        };\n";

  pimpl -> state.SetNull();
  pimpl -> variables = pimpl -> variables -> getPrevLevel();
  pimpl -> indent -= 2;
}

void GeneratorStd::leaveCase() {
  OASSERT_1(!pimpl -> suite.IsNull() && !pimpl -> testcase.IsNull() && pimpl -> state.IsNull());

  *pimpl -> output
      << "\n"
      << "      public:\n"
      << "        explicit " << pimpl -> testcase << "(\n"
      << "            const ::OTest2::Context& context_,\n"
      << "            " << pimpl -> suite << "* suite_) :\n"
      << "          ::OTest2::CaseGenerated(context_)";
  pimpl -> variables -> printInitializers(*pimpl -> output, pimpl -> indent + 1);
  *pimpl -> output
      << " {"
      << pimpl -> case_ctor
      << "        }\n"
      << "\n"
      << "        virtual ~" << pimpl -> testcase << "() {"
      << pimpl -> case_dtor
      << "        }\n"
      << "    };\n";

  pimpl -> testcase.SetNull();
  pimpl -> variables = pimpl -> variables -> getPrevLevel();
  pimpl -> indent -= 2;
}

void GeneratorStd::leaveSuite() {
  OASSERT_1(!pimpl -> suite.IsNull() && pimpl -> testcase.IsNull() && pimpl -> state.IsNull());

  *pimpl -> output
      << "\n"
      << "  public:\n"
      << "    explicit " << pimpl -> suite << "(\n"
      << "        const ::OTest2::Context& context_) :\n"
      << "      ::OTest2::SuiteGenerated(context_)";
  pimpl -> variables -> printInitializers(*pimpl -> output, pimpl -> indent + 1);
  *pimpl -> output
      << " {"
      << pimpl -> suite_ctor
      << "    }\n"
      << "\n"
      << "    virtual ~" << pimpl -> suite << "() {"
      << pimpl -> suite_dtor
      << "    }\n"
      << "};\n";

  pimpl -> suite.SetNull();
  pimpl -> variables = 0;
  pimpl -> indent -= 2;
}

void GeneratorStd::appendVariable(
    const dstring& name_,
    const DeclarationPtr& declaration_) {
  pimpl -> variables -> appendVariable(name_, declaration_);
}

void GeneratorStd::finishDeclarations() {
  pimpl -> variables -> printDeclarations(*pimpl -> output, pimpl -> indent);
  *pimpl -> output << '\n';
}

bool GeneratorStd::setInitializer(
    const dstring& name_,
    const dstring& body_) {
  return pimpl -> variables -> setInitializer(name_, body_);
}

void GeneratorStd::setCtorBody(
    const dstring& body_) {
  OASSERT_1(!body_.IsNull());

  if(!pimpl -> state.IsNull())
    pimpl -> state_ctor = body_;
  else if(!pimpl -> testcase.IsNull())
    pimpl -> case_ctor = body_;
  else if(!pimpl -> suite.IsNull())
    pimpl -> suite_ctor = body_;
  else
    OASSERT_NEVER();
}

void GeneratorStd::setDtorBody(
    const dstring& body_) {
  OASSERT_1(!body_.IsNull());

  if(!pimpl -> state.IsNull())
    pimpl -> state_dtor = body_;
  else if(!pimpl -> testcase.IsNull())
    pimpl -> case_dtor = body_;
  else if(!pimpl -> suite.IsNull())
    pimpl -> suite_dtor = body_;
  else
    OASSERT_NEVER();
}

} /* -- namespace OTest2 */
