# -- site description
title: OTest2
subtitle: C++ testing framework
name: Staon (Ondrej Starek)
email: stareko@email.cz
description: >- # this means to ignore newlines until "baseurl:"
  OTest2 is small C++ framework for writing automated tests.

# -- public address of the project's github pages
url: "https://staon.github.io"
baseurl: "/otest2"

# -- the repository of the OTest2 project
repository: "Staon/otest2"
repositoryurl: "http://github.com/Staon/otest2"

#twitter_username: jekyllrb
github_username: Staon

# -- author side bar
author:
  name: "Staon"
  avatar: "/images/face.jpg"
  location : "Prague, The Czech Republic"

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.19.1"
plugins:
  - jekyll-include-cache
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      toc: false
      classes: wide
      sidebar:
        nav: "docs"
